import { StyleSheet } from "react-native";
import { font, color } from "../../theme/color";

export const screenStyle = (
  scale: (val: number) => number,
  fontSize: (val: number) => number,
  isDesktop: boolean,
  isMobile: boolean,
  doctors: any,
) =>
StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  scrollContent: { padding: 0 },
  heading: {
    fontSize: fontSize(22),
    fontFamily: font.Rubik_600sb,
    marginBottom: 16,
    color: '#28252C',
    padding: 16,
  },
  tableContent: {
    ...(isDesktop && { flex: 1 }),
    paddingHorizontal: fontSize(16),
  },
  table: {
    minWidth: fontSize(doctors.length * 300 + 160),
    flex: 1,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    borderRadius: 12,
    overflow: 'hidden',
    paddingVertical: fontSize(20),
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EAEAEA',
    paddingVertical: fontSize(12),
    paddingHorizontal: fontSize(10),
    alignItems: 'center',
  },
  labelCell: {
    width: fontSize(160),
    paddingRight: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  infoCell: {
    paddingHorizontal: fontSize(6),
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexShrink: 0,
    flex: 1,
  },
  labelText: {
    fontSize: fontSize(14),
    fontFamily: font.Rubik_600sb,
    color: '#28252C',
  },
  doctorImage: {
    width: fontSize(60),
    height: fontSize(60),
    borderRadius: fontSize(30),
    marginBottom: 6,
  },
  doctorName: {
    fontSize: fontSize(14),
    fontFamily: font.Rubik_600sb,
    color: '#28252C',
  },
  doctorSub: {
    fontSize: 13,
    color: '#535156',
    marginTop: 4,
  },
  ratingBox: { flexDirection: 'row', alignItems: 'center' },
  ratingValue: {
    backgroundColor: color.color_38C172,
    color: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    fontSize: fontSize(14),
    fontFamily: font.Rubik_500m,
  },
  ratingReviews: {
    fontSize: fontSize(16),
    fontFamily: font.Rubik_400r,
    color: color.color_827C8A,
    marginLeft: 8,
  },
  rowValue: {
    fontSize: fontSize(16),
    fontFamily: font.Rubik_500m,
    color: color.color_28252C,
    fontWeight: '500',
    width: fontSize(140),
    overflow: 'hidden',
  },
  rowSub: {
    fontSize: fontSize(16),
    fontFamily: font.Rubik_500m,
    color: color.color_28252C,
  },
  additionalRatingsRow: { alignItems: 'flex-start', borderBottomWidth: 0 },
  additionalRatingsColumn: {
    flex: 1,
    paddingLeft: 6,
    alignItems: 'flex-start',
    minWidth: fontSize(150),
  },
  ratingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    width: '100%',
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: fontSize(14 * 5 + 2 * 4),
    marginRight: 8,
    flexShrink: 0,
  },
  ratingLabel: {
    fontSize: fontSize(13),
    fontFamily: font.Rubik_400r,
    color: color.color_28252C,
  },
  contentCol: {
    flex: 1,
    alignItems: 'flex-start',
    minWidth: isMobile ? fontSize(100) : fontSize(180),
  },
  button: {
    paddingVertical: isMobile ? fontSize(8) : fontSize(12),
    paddingHorizontal: fontSize(12),
    borderRadius: fontSize(4),
    minWidth: isMobile ? fontSize(100) : fontSize(200),
    marginBottom: fontSize(8),
  },
  pink: { backgroundColor: '#FF008A' },
  gray: { backgroundColor: '#eee' },
  buttonText: {
    fontSize: fontSize(16),
    fontFamily: font.Rubik_500m,
    color: color.white,
    textAlign: 'center',
  },
  blackText: { color: color.lable1 },
  link: {
    fontSize: fontSize(16),
    textAlign: 'left',
    marginTop: fontSize(4),
    textDecorationLine: 'underline',
    fontFamily: font.Rubik_400r,
    color: color.color_28252C,
  },

     scrollContainer: {
      flexGrow: 1,
      paddingBottom: fontSize(40),
      marginHorizontal: fontSize(10),
    },
    headerContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: fontSize(20),
    },
    bodyContainer: {
      marginVertical: fontSize(4),
      justifyContent: "space-between",
      flexDirection: isMobile?"column":"row",
    },
        title: {
      fontSize: fontSize(26),
      fontFamily: font.Rubik_600sb,
      color: color.color_28252C,
    },
      formLabel: {
      color: color.color_28252C,
      fontSize: fontSize(16),
      fontFamily: font.Rubik_400r,
      marginTop: fontSize(20),
    },

      consultancyTypeSelectionBox: {
      width: "100%",
      height: fontSize(65),
      justifyContent: "center",
      alignItems: "center",
      marginVertical: fontSize(10),
      borderRadius: fontSize(10),
      borderColor: "#E0DEE2",
      borderWidth: fontSize(1),
      backgroundColor: color.white,
    },
     consultancyTypeRow: {
      width: "98%",
      height: fontSize(58),
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: fontSize(5),
    },
    consultancyTypeButton: {
      flex: 1,
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: fontSize(10),
    },
    consultancyTypeTextInactive: {
      color: color.color_28252C,
      fontSize: fontSize(16),
      fontFamily: font.Rubik_400r,
      textAlign: "center",
    },
    consultancyTypeTextActive: {
      color: color.white,
      fontSize: fontSize(16),
      fontFamily: font.Rubik_400r,
      textAlign: "center",
    },
      dropdownWrapper: {
      zIndex: 1000,
      marginBottom: fontSize(16),
    },
       dropdown: {
      zIndex: 1000,
      elevation: fontSize(5),
    },
       policyText: {
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      fontSize: fontSize(16),
    },
    policyText1: {
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      fontSize: fontSize(16),
      flex: 1,
    },
        scheduleAppointmentButton: {
      width: "100%",
      height: fontSize(60),
      backgroundColor: color.color_FF008A,
      marginTop: fontSize(16),
      borderRadius: fontSize(10),
      justifyContent: "center",
    },
      scheduleButtonText: {
      color: color.white,
      fontSize: fontSize(20),
      fontFamily: font.Rubik_500m,
      textAlign: "center",
    },
       slotSelectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignContent: "center",
      paddingBottom: fontSize(10),
    },
    selectedSlotDateText: {
      color: color.color_28252C,
      fontSize: fontSize(12),
      fontFamily: font.Rubik_400r,
      marginTop: fontSize(20),
    },
         otherLabel: {
      color: color.color_28252C,
      fontSize: fontSize(14),
      fontFamily: font.Rubik_400r,
    },
});
