import { StyleSheet } from "react-native";
import { font, color } from "../../theme/color";

export const screenStyle = (
  isTablet: any,
  isMobile: any,
  isMobileOrTablet: any,
  isDesktop: any,
  scale: any,
  
) =>
  StyleSheet.create({
    container: { flex: 1 },
    contentWrapper: { alignItems: "center" },
    bodyWrapper: {
      width: "100%",
      paddingHorizontal: isMobileOrTablet ? scale(30) : scale(100),
      flexDirection: isMobileOrTablet ? "column" : "row",
    },
    leftColumn: { ...(isDesktop && { flex: 0.7 }), flexShrink: 1, padding: 10 },
    rightColumn: {
      ...(isDesktop && { flex: 0.38 }),
      ...(isMobileOrTablet && { flex: 1 }),
    },
    appointmentSectionWrapper: {
      backgroundColor: color.colorF9F9F9,
   //   backgroundColor: color.color_e0e0e0,
      flexShrink: 1,
      borderRadius: scale(8),
      paddingHorizontal: scale(16),
      paddingVertical: scale(30),
      marginTop: scale(30),
      marginBottom: scale(15),
    },
    appointmentSectionWrapper2: {
      backgroundColor: color.colorF9F9F9,
   //   backgroundColor: color.color_e0e0e0,
      flexShrink: 1,
      borderRadius: scale(8),
      paddingHorizontal: scale(16),
      paddingVertical: scale(30),
      marginTop: scale(30),
      marginBottom: scale(15),
    },
    joinWaitlistSectionWrapper: {
      backgroundColor: color.color_e0e0e0,
      flexShrink: 1,
      borderRadius: scale(8),
      paddingHorizontal: scale(16),
      paddingVertical: scale(30),
      marginTop: scale(30),
      marginBottom: scale(15),
    },
    footerSection: { width: "100%", height: "auto" },
    tabsContainer: {
      flexDirection: "row",
      borderBottomColor: "#eee",
      borderBottomWidth: 1,
      backgroundColor:color.white
    },
    tabItem: {
      flex: 1,
      paddingVertical: scale(20),
      alignItems: "center",
      borderBottomWidth: 3,
      borderBottomColor: "#EEEEEE",
    },
    activeTabItem: {
      borderBottomColor: color.color_FF008A,
      borderBottomWidth: scale(3),
    },
    tabText: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
    //  marginVertical: scale(20),
    },
    reviewsCountText: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      paddingLeft: scale(12),
    },
    totalLocationsText: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      marginVertical: scale(10),
      flex: 1,
    },
    activeTabText: {
      fontSize: scale(16),
      fontFamily: font.Rubik_500m,
      color: color.color_FF008A,
    },
    flex1: { flex: 1 },
    sectionOverviewItem: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      paddingVertical: scale(18),
      paddingHorizontal: scale(16),
      backgroundColor: color.white,
      borderColor: "#EEEEEE",
      borderWidth: scale(1),
      borderRadius: scale(5),
      marginBottom: scale(14),
    },
        sectionOverviewItemActive: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      paddingVertical: scale(18),
      paddingHorizontal: scale(16),
      backgroundColor: color.white,
      borderColor: "#EEEEEE",
      borderWidth: scale(1),
      borderRadius: scale(5),
      marginBottom: scale(14)
    },
    overviewDropdownHeader: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      paddingVertical: scale(18),
      paddingHorizontal: scale(8),
      marginVertical: scale(10),
    },
    overviewDropdownContainer: {
      width: "100%",
      backgroundColor: color.white,
      paddingVertical: scale(6),
      paddingHorizontal: scale(10),
      borderRadius: scale(5),
      marginBottom: scale(10),
    },
    overviewDropdownList: {
      width: "100%",
      backgroundColor: color.white,
      marginVertical: scale(4),
    },
    overviewText: {
      color: color.color_28252C,
      fontSize: scale(16),
      fontFamily: font.Rubik_500m,
      flex: 1,
      marginHorizontal: 10,
    },
    overviewDropdownHeaderText: {
      color: color.color_FF008A,
      fontSize: scale(16),
      fontFamily: font.Rubik_500m,
      flex: 1,
      marginHorizontal: 10,
    },
    scheduleAppointmentTitle: {
      color: color.color_28252C,
      fontSize: scale(24),
      fontFamily: font.Rubik_500m,
      marginTop: scale(10),
    },
    scheduleAppointmentSubTitle: {
      color: color.color_28252C,
      fontSize: scale(14),
      fontFamily: font.Rubik_400r,
      marginTop: scale(10),
    },
        marginVertical4: { marginVertical: scale(4) },

    formLabel: {
      color: color.color_28252C,
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      marginTop: scale(20),
    },
    joinWaitlistPrompt: {
      color: color.color_28252C,
      fontSize: scale(18),
      fontFamily: font.Rubik_400r,
      marginTop: scale(20),
      textAlign: "center",
      paddingHorizontal: scale(10),
    },
    scheduleButtonText: {
      color: color.white,
      fontSize: scale(20),
      fontFamily: font.Rubik_500m,
      textAlign: "center",
    },
    joinWaitlistButtonText: {
      color: color.lable1,
      fontSize: scale(20),
      fontFamily: font.Rubik_500m,
      textAlign: "center",
    },
    slotSelectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignContent: "center",
      paddingBottom: scale(10),
      marginHorizontal: scale(14),
    },
    selectedSlotDateText: {
      color: color.color_28252C,
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      marginTop: scale(20),
    },
    consultancyTypeSelectionBox: {
      width: "100%",
      height: scale(65),
      justifyContent: "center",
      alignItems: "center",
      marginVertical: scale(10),
      borderRadius: scale(10),
      borderColor: "#E0DEE2",
      borderWidth: scale(1),
      backgroundColor: color.white,
    },
    dropdownInputContainer: {
      width: "100%",
      height: scale(65),
      justifyContent: "center",
      alignItems: "center",
      marginVertical: scale(10),
      borderRadius: scale(10),
      borderColor: "#E0DEE2",
      borderWidth: scale(1),
      backgroundColor: color.white,
    },
    modalDropdownStyle: { width: "100%" },
    dropdownMenuStyle: {
      maxHeight: 200,
      borderRadius: 10,
      backgroundColor: color.white,
      marginTop: 5,
    },
    modalDropdownTextStyle: {
      fontSize: scale(12),
      color: color.lable1,
      fontFamily: font.Rubik_500m,
    },
    consultancyTypeRow: {
      width: "98%",
      height: scale(58),
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: scale(5),
    },
    consultancyTypeButton: {
      flex: 1,
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: scale(10),
    },
    consultancyTypeTextInactive: {
      color: color.color_28252C,
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      textAlign: "center",
    },
    consultancyTypeTextActive: {
      color: color.white,
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      textAlign: "center",
    },
    overviewTextActive: {
      color: color.color_00D193,
      fontSize: scale(16),
      fontFamily: font.Rubik_500m,
      flex: 1,
      marginHorizontal: 10,
    },
    overviewIconActive: { height: scale(24), width: scale(24) },
    overviewIcon: { height: scale(24), width: scale(24) },
    doctorProfileCard: {
      flexDirection:isMobile?"column":"row",
      padding: 15,
      borderBottomColor: "#eee",
      borderBottomWidth: 1,
      backgroundColor: "#fff",
      alignItems:"center"
    
    },
    fileIcon: { width: scale(50), height: scale(50), borderRadius: scale(13) },
    doctorImage: {
      width: scale(150),
      height: scale(150),
      borderRadius: scale(13),
      backgroundColor: "#ddd",
    },
    doctorName: {
      fontFamily: font.Rubik_500m,
      fontSize: scale(24),
      color: color.color_28252C,
    },
    doctorSpecialty: {
      color: color.color_535156,
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      marginTop: scale(4),
      marginLeft: scale(4),
    },
    ratingAndReviewsRow: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: scale(10),
    },
    ratingBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: color.color_00D193,
      borderRadius: scale(8),
      paddingHorizontal: scale(6),
      paddingVertical: scale(2),
    },
    ratingText: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.white,
      marginLeft: scale(6),
    },
    reviewsTitle: {
      fontSize: scale(20),
      fontFamily: font.Rubik_500m,
      color: color.color_28252C,
    },
    reviewsHeader: { flexDirection: "row", paddingTop: scale(20) },
    ratingGreen: {
      textAlign: "center",
      fontSize: scale(30),
      fontFamily: font.Rubik_700b,
      color: color.color_00D193,
    },
    ratingOutOfText: {
      fontSize: scale(14),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      paddingVertical: scale(4),
      textAlign: "center",
    },
    reviewCountText: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      paddingVertical: scale(4),
      flex: 1,
    },
    mostRelevantText: {
      fontSize: scale(14),
      fontFamily: font.Rubik_400r,
      color: color.color_9327FF,
      paddingVertical: scale(4),
      marginHorizontal: scale(5),
    },
    doctorInfoColumn: { flex: 1, marginLeft: 15,
      ...(isMobile && {  marginTop: scale(10),}),
     },
    doctorNameRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
    },
    hospitalText: {
      fontSize: scale(14),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      flex: 1,
    },
    availabilityTime: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.color_535156,
      marginLeft: scale(5),
    },
    callUsOnlable: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_535156,
      marginLeft: scale(5),
    },
    videoConsultBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F2E7FE",
      borderRadius: 5,
      marginRight: scale(6),
      paddingHorizontal: scale(6),
      paddingVertical: scale(2),
    },
    videoConsultBadgeText: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.color_761FCC,
      marginLeft: scale(10),
    },
    inPersonBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FFE6F3",
      borderRadius: 5,
      marginRight: scale(6),
      paddingHorizontal: scale(6),
      paddingVertical: scale(2),
    },
    inPersonBadgeText: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.color_FF008A,
      marginLeft: scale(10),
    },
    scheduleAppointmentButton: {
      width: "100%",
      height: scale(60),
      backgroundColor: color.color_FF008A,
      marginTop: scale(16),
      borderRadius: scale(10),
      justifyContent: "center",
    },
    joinWaitlistImageWrapper: {
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      marginTop: scale(20),
    },
    joinWaitlistButtonWrapper: {
      width: "100%",
      height: scale(60),
      backgroundColor: color.white,
      marginTop: scale(16),
      borderRadius: scale(10),
      justifyContent: "center",
    },
    locationCard: { width: "auto", paddingVertical: scale(10) },
    locationName: {
      fontSize: scale(16),
      fontFamily: font.Rubik_500m,
      color: color.color_28252C,
    },
    locationAddress: {
      fontSize: scale(14),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      marginTop: scale(8),
    },
    progressBarContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: scale(10),
    },
    progressWrapper: {
      flex: 0.5,
      marginHorizontal: scale(10),
      flexDirection: "row",
      alignItems: "center",
    },
    progressFill: {
      height: scale(8),
      backgroundColor: "#00ffae",
      borderRadius: scale(10),
    },
    ratingLabel: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      width: scale(100),
    },
    ratingValueText: {
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      marginLeft: scale(10),
    },
    reviewCard: {
      borderRadius: scale(10),
      padding: scale(12),
      marginBottom: scale(20),
    },
    reviewUserRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: scale(8),
    },
    userAvatar: {
      width: scale(70),
      height: scale(70),
      borderRadius: scale(35),
      marginRight: scale(10),
    },
    userName: {
      color: color.color_212121,
      fontSize: scale(14),
      fontFamily: font.Rubik_500m,
    },
    reviewDate: {
      color: color.color919191,
      fontSize: scale(12),
      fontFamily: font.Rubik_400r,
      marginTop: scale(6),
    },
    reviewStarsRow: { flexDirection: "row", marginBottom: scale(6) },
    reviewText: {
      color: color.color_28252C,
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      lineHeight: scale(24),
    },
    dynamicContentContainer: { flexShrink: 1 },
    sectionTitle: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      marginVertical: scale(20),
    },
    locationHeader: { flexDirection: "row", paddingTop: scale(20) },
    locationArrowIcon: { marginLeft: scale(20), marginTop: 4 },
    mapContainer: {
      width: "100%",
      height: scale(300),
      borderRadius: scale(12),
    },
    reviewSummaryRow: { flexDirection: "row", width: "100%" },
    ratingSummaryColumn: {
      flex: 0.2,
      justifyContent: "center",
      alignItems: "center",
    },
    ratingBarsColumn: { flex: 1, marginLeft: isMobile ? scale(10) : 0 },
    ratingBarsList: { paddingVertical: 10 },
    reviewFilterRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: scale(15),
      alignItems: "center",
    },
    mediaHeader: { flexDirection: "row", paddingTop: scale(20) },
    mediaTitle: {
      fontSize: scale(16),
      fontFamily: font.Rubik_400r,
      color: color.color_28252C,
      marginVertical: scale(10),
      flex: 1,
    },
    mediaArrowIcon: { marginLeft: scale(20), marginTop: 4 },
    doctorSpecialtyRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
    },
    heartIcon: { marginLeft: scale(20), marginTop: 4 },
    hospitalInfoRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      marginVertical: scale(4),
    },
    availabilityRow: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: scale(4),
    },
    policyText: {
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      fontSize: scale(16),
    },
    policyText1: {
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      fontSize: scale(16),
      flex: 1,
    },
    containerDropdown1: { paddingVertical: scale(15) },
    iconWrapper: { alignItems: "center", marginBottom: 20 },
    labelBooking: {
      fontSize: scale(30),
      color: color.lable1,
      fontFamily: font.Rubik_400r,
      textAlign: "center",
    },
    labelBookingDetails: {
      fontSize: scale(14),
      marginVertical: scale(6),
      color: color.color_28252C70,
      fontFamily: font.Rubik_300l,
      textAlign: "center",
    },
    labelPlaceholder: {
      fontSize: scale(16),
      marginBottom: scale(6),
      color: color.lable1,
      fontFamily: font.Rubik_400r,
    },
    dropdown: { zIndex: 1000, elevation: 5 },
    dropdownHighlightText: { fontSize: scale(14),
      color: '#333',
      fontFamily: font.Rubik_400r,
      textAlign:'left',},
    dropdownCountry: { 
      fontSize: scale(14),
      color: '#333',
      fontFamily: font.Rubik_400r,
    },
       iconImage: {
      width: scale(20),
      height: scale(20),
      marginHorizontal: scale(6),
    },
        calltext: {
      fontSize: scale(16),
      
      color: color.color_FF008A,
      fontFamily: font.Rubik_500m,
      paddingHorizontal:scale(20)
    },
  });
