import { StyleSheet } from "react-native";
import { font, color } from "../../theme/color";

export const screenStyle = (
  isTablet: any,
  isMobile: any,
  isMobileOrTablet: any,
  isDesktop: any,
  scale: any
) =>
  StyleSheet.create({
    container: { flex: 1 },
    contentWrapper: { alignItems: "center" },
    bodyWrapper: {
      flex: 1,
      width: "100%",
      paddingHorizontal: isMobileOrTablet ? scale(30) : scale(100),
      flexDirection: isMobileOrTablet ? "column" : "row",
    },
    leftColumn: { ...(isDesktop && { flex: 0.7 }), flexShrink: 1, padding: 20 },
    rightColumn: {
      ...(isDesktop && { flex: 0.38 }),
      ...(isMobileOrTablet && { flex: 1 }),
    },
    footerSection: { width: "100%", height: "auto" },
    flex1: { flex: 1 },
    leftTopSection: { paddingVertical: scale(15) },
    profileCardrow: { justifyContent: "space-between", marginBottom: 12 },
    aboutyouText: {
      color: color.color_28252C,
      fontSize: scale(30),
      fontFamily: font.Rubik_500m,
      marginBottom: scale(10),
    },
    card: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "white",
      padding: 16,
      borderRadius: scale(8),
      borderWidth: 1,
      borderColor: "#E0E0E0",
      width: "48%",
      minHeight: scale(48),
    },
    cardMobile: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "white",
      padding: 16,
      borderRadius: scale(8),
      borderWidth: 1,
      borderColor: "#E0E0E0",
      width: "96%",
      minHeight: scale(48),
      marginBottom: scale(10),
    },
    nameActive: {
      fontSize: scale(16),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
    },
    nameSomeonetext: {
      fontSize: scale(16),
      color: color.color_28252C60,
      fontFamily: font.Rubik_400r,
    },
    radio: {
      width: scale(20),
      height: scale(20),
      borderRadius: scale(10),
      borderWidth: 1,
      borderColor: "#CCC",
      alignItems: "center",
      justifyContent: "center",
    },
    selectedRadio: { backgroundColor: "#00D084", borderColor: "#00D084" },
    marginVertical4: { marginVertical: scale(4) },
    marginVertical20: { marginVertical: scale(20) },
    marginVertical10: { marginVertical: scale(10) },
    marginVertical14: { marginVertical: scale(14) },
    dropdown: { zIndex: 1000, elevation: 5 },
    inputDropdownWrapper: { flex: 1, marginRight: scale(10) },
    label: {
      fontSize: scale(16),
      marginBottom: scale(6),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      flex: 1,
    },
    labelup: {
      fontSize: scale(14),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      flex: 1,
                     ...(isMobile && {   marginTop: scale(15),}),

    },
    labelDown: {
      fontSize: scale(14),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
    },
    uploadContainer2: {
      flexDirection:isMobile?"column":"row",
   
      justifyContent: "center",
      borderRadius: scale(8),
      paddingHorizontal: scale(12),
      paddingVertical: scale(4),
      minHeight: scale(50),
      backgroundColor: "#ececec",
      marginVertical: scale(15),
         ...(!isMobile && { alignItems: "center",}),
    },
    downloadContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#E0DEE2",
      borderRadius: scale(8),
      paddingHorizontal: scale(12),
      paddingVertical: scale(8),
      backgroundColor: "#fff",
      justifyContent: "center",
               ...(isMobile && {   marginVertical: scale(15),}),

    },
    uploadContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: scale(8),
      paddingHorizontal: scale(12),
      height: scale(48),
      backgroundColor: "#fff",
    },
    uploadText: {
      color: "#FF007A",
      fontSize: scale(14),
      fontFamily: font.Rubik_500m,
    },
    dropdownText: {
      fontSize: scale(14),
      color: color.lable1,
      fontFamily: font.Rubik_400r,
      flex: 1,
    },
    placeholderText: {
      color: color.color_E0DEE2,
      fontSize: scale(14),
      fontFamily: font.Rubik_400r,
      flex: 1,
    },
    compareCard: {
      backgroundColor: color.white,
      borderRadius: scale(10),
      padding: scale(12),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: isMobileOrTablet ? scale(10) : scale(20),
      height: scale(80),
      marginRight: isDesktop ? scale(10) : scale(0),
      marginBottom: 10,
    },
    compareCardAvatar: {
      width: scale(50),
      height: scale(50),
      borderRadius: scale(10),
      marginRight: scale(10),
    },
    compareCardTextContainer: { flex: 1 },
    compareCardName: {
      color: "#28252C",
      fontFamily: font.Rubik_400r,
      fontSize: scale(16),
    },
    compareCardSpecialty: {
      fontSize: scale(14),
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      marginTop: scale(5),
    },
    lableGray: {
      color: "#28252C80",
      fontFamily: font.Rubik_400r,
      fontSize: scale(14),
    },
    appointmentTimeView: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    labelblack: {
      fontSize: scale(14),
      marginTop: scale(6),
      color: color.lable1,
      fontFamily: font.Rubik_400r,
      flex: 1,
    },
    labelChangeSlot: {
      fontSize: scale(14),
      marginTop: scale(6),
      color: color.color_FF008A,
      fontFamily: font.Rubik_500m,
    },
    policyText: {
      color: color.color_28252C,
      fontFamily: font.Rubik_400r,
      fontSize: scale(16),
      
    },
    scheduleAppointmentTitle: {
      color: color.color_28252C,
      fontSize: scale(24),
      fontFamily: font.Rubik_500m,
    },
    labelChangeSlot2: {
      fontSize: isMobileOrTablet ? scale(26) : scale(36),
      color: color.color_28252C,
      fontFamily: font.Rubik_500m,
    },
  });
