import React from 'react';
import {FavoriteGroup} from '../screens/profile/components/FavProduct';

const userData = [
  {
    id: 1,
    fullName: 'Dhaval Sarvaiya',
    phoneNumber: '+91 9687174523',
    email: 'sarvaiyadhaval167@gmail.com',
    country: 'India',
    city: 'Rajkot',
    zipCode: '360002',
    address: '12 Green Park Society, Kalawad Road',
    password: 'Dhaval123',
    confirmPassword: 'Dhaval123',
    profilePicture: 'https://media.licdn.com/dms/image/v2/D4D03AQHwe_hi6EBNbQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1715333081151?e=2147483647&v=beta&t=y6_Yo_rb1ctRVA59l9cIL9U-Q2gLFqSnaUeetvKacZ4',
    type: 'doctor',
  },
  {
    id: 2,
    fullName: 'Priya Patel',
    phoneNumber: '9876543210',
    email: 'priya.patel@example.com',
    country: 'India',
    city: 'Ahmedabad',
    zipCode: '380015',
    address: '21 Shivam Residency, Maninagar',
    password: 'Priya123',
    confirmPassword: 'Priya123',
    profilePicture: 'https://images.unsplash.com/photo-1572009283538-2fce2d2a1909?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    type: 'patient',
  },
  {
    id: 3,
    fullName: 'Rohan Mehta',
    phoneNumber: '9123456780',
    email: 'rohan.mehta@example.com',
    country: 'India',
    city: 'Surat',
    zipCode: '395007',
    address: '45 Vipul Nagar, Piplod',
    password: 'Rohan123',
    confirmPassword: 'Rohan123',
    type: 'doctor',
  },
  {
    id: 4,
    fullName: 'Sneha Desai',
    phoneNumber: '9012345678',
    email: 'sneha.desai@example.com',
    country: 'India',
    city: 'Vadodara',
    zipCode: '390005',
    address: '34 Sunrise Avenue, Gotri Road',
    password: 'Sneha123',
    confirmPassword: 'Sneha123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'patient',
  },
  {
    id: 5,
    fullName: 'Kunal Shah',
    phoneNumber: '9988776655',
    email: 'kunal.shah@example.com',
    country: 'India',
    city: 'Mumbai',
    zipCode: '400001',
    address: '90 Ocean Heights, Marine Drive',
    password: 'Kunal123',
    confirmPassword: 'Kunal123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'doctor',
  },
  {
    id: 6,
    fullName: 'Anjali Joshi',
    phoneNumber: '8899776655',
    email: 'anjali.joshi@example.com',
    country: 'India',
    city: 'Pune',
    zipCode: '411001',
    address: '78 Rose Garden, Baner',
    password: 'Anjali123',
    confirmPassword: 'Anjali123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'patient',
  },
  {
    id: 7,
    fullName: 'Vikas Kumar',
    phoneNumber: '9090909090',
    email: 'vikas.kumar@example.com',
    country: 'India',
    city: 'Delhi',
    zipCode: '110001',
    address: '67 Maple Tower, Connaught Place',
    password: 'Vikas123',
    confirmPassword: 'Vikas123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'doctor',
  },
  {
    id: 8,
    fullName: 'Neha Verma',
    phoneNumber: '9876541230',
    email: 'neha.verma@example.com',
    country: 'India',
    city: 'Noida',
    zipCode: '201301',
    address: '123 Sector 62, TechZone',
    password: 'Neha123',
    confirmPassword: 'Neha123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'patient',
  },
  {
    id: 15,
    fullName: 'Mehulkumar',
    phoneNumber: '9876541230',
    email: 'mehul@gmail.com',
    country: 'India',
    city: 'Noida',
    zipCode: '201301',
    address: '123 Sector 62, TechZone',
    password: 'Test123',
    confirmPassword: 'Test123',
    profilePicture: 'https://img.freepik.com/free-photo/portrait-smiling-handsome-male-doctor-man_171337-5055.jpg?ga=GA1.1.499059121.1745404553&semt=ais_hybrid&w=740',
    type: 'patient',
  },
  {
    id: 9,
    fullName: 'Rajeev Reddy',
    phoneNumber: '9765432109',
    email: 'rajeev.reddy@example.com',
    country: 'India',
    city: 'Hyderabad',
    zipCode: '500001',
    address: '10 Lake View Colony, Banjara Hills',
    password: 'Rajeev123',
    confirmPassword: 'Rajeev123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'doctor',
  },
  {
    id: 10,
    fullName: 'Divya Nair',
    phoneNumber: '9654321098',
    email: 'divya.nair@example.com',
    country: 'India',
    city: 'Kochi',
    zipCode: '682001',
    address: '56 Palm Beach Road, Vytilla',
    password: 'Divya123',
    confirmPassword: 'Divya123',
    profilePicture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSid6-Znx29CYPj6CZGMjouUXXf2evX1JaqA0upYdPClk0lcs7zwM1HGzmwUns4p2w18&usqp=CAU',
    type: 'patient',
  },
];

const favoriteGroups: FavoriteGroup[] = [
  {
    id: 'group1',
    name: 'Orthopedics',
    doctors: [
      {
        id: 'doc1',
        name: 'Dr. Deniz Warren (MD)',
        specialty: 'Cardiologist',
        distance: '0.2 Mi',
        rating: '4.6',
        reviews: 204,
        address:
          'Heart Plus Hospital, 73-09 Myrtle Avenue, 1st Floor, Glendale, NY 11385',
        hours: '9:00 AM - 5:00 PM',
        videoConsultant: true,
        inPerson: true,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
      {
        id: 'doc2',
        name: 'Dr. Smeeth Chessy (MS)',
        specialty: 'Cardiologist',
        distance: '0.2 Mi',
        rating: '4.6',
        reviews: 204,
        address: '104 Delancey St, New York, NY 1002',
        hours: '9:00 AM - 5:00 PM',
        videoConsultant: true,
        inPerson: true,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
    ],
  },
  {
    id: 'group3',
    name: 'Dentists',
    doctors: [
      {
        id: 'doc5',
        name: 'Dr. Emma Johnson (DDS)',
        specialty: 'Dentist',
        distance: '0.5 Mi',
        rating: '4.8',
        reviews: 156,
        address: '123 Broadway, New York, NY 10001',
        hours: '9:00 AM - 5:00 PM',
        videoConsultant: true,
        inPerson: true,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
      {
        id: 'doc6',
        name: 'Dr. Michael Smith (DMD)',
        specialty: 'Dental Surgeon',
        distance: '0.8 Mi',
        rating: '4.9',
        reviews: 189,
        address: '456 Park Avenue, New York, NY 10022',
        hours: '8:00 AM - 4:00 PM',
        videoConsultant: true,
        inPerson: true,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
    ],
  },
  {
    id: 'group4',
    name: 'Eye Specialist',
    doctors: [
      {
        id: 'doc7',
        name: 'Dr. Sarah Wilson (MD)',
        specialty: 'Ophthalmologist',
        distance: '0.4 Mi',
        rating: '4.7',
        reviews: 132,
        address: '789 5th Avenue, New York, NY 10065',
        hours: '9:00 AM - 6:00 PM',
        videoConsultant: true,
        inPerson: true,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
      {
        id: 'doc8',
        name: 'Dr. James Brown (OD)',
        specialty: 'Optometrist',
        distance: '0.6 Mi',
        rating: '4.5',
        reviews: 98,
        address: '321 Lexington Avenue, New York, NY 10016',
        hours: '10:00 AM - 7:00 PM',
        videoConsultant: true,
        inPerson: false,
        image:
          'https://images.unsplash.com/photo-1612523138351-4643808db8f3?w=900&auto=format&fit=crop&q=60',
      },
    ],
  },
];

export {userData, favoriteGroups};
